### ISSUE TITLE
PTR Update 2.11 Not working

### ISSUE THREAD

**Issue by Metadraconis** [MrCoolGoat/MapMod#3]
After PTR Update 2.11 Maps just wont load anymore. UI seems fine? Dont have a Debugger at Hand rn but it seems Like the function to load the Maps isnt starting at all or there might be pathing issues ending the function prematurely.

**Comment by Zi9** [comment]
Fixed in v1.7. (https://github.com/MrCoolGoat/MapMod/releases/tag/v1.7.0)

Closing issue.
