### ISSUE TITLE
PTR Update didnt move anything?

### ISSUE THREAD

**Issue by JunoEclips3** [MrCoolGoat/MapMod#5]
[](url
![Drift Racing Online 13_12_2021 13_07_46](https://user-images.githubusercontent.com/96022621/145818197-3fceb9e3-faf5-4709-97e1-5675874a4f13.png)
)
when i saw the PTR update for map mod, i was hoping it would move the button so i can more eazly pick modded lobbys or the top 32 thing. im kinda surprised that it didnt move at all.

**Comment by Zi9** [comment]
Are you sure you replaced all the files with the ones from the update?

**Comment by Zi9** [comment]
Closed due to inactivity
